# Generated by Django 4.2.5 on 2024-01-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=40)),
                ('stdname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.deptmodel')),
            ],
        ),
    ]
