# Generated by Django 4.2.5 on 2024-01-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptmodel',
            old_name='did',
            new_name='Department_Id',
        ),
        migrations.RenameField(
            model_name='deptmodel',
            old_name='dname',
            new_name='Department_Name',
        ),
    ]
