# Generated by Django 4.2.5 on 2024-01-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_rename_did_deptmodel_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='stdname',
            new_name='Student_Department',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='stid',
            new_name='Student_Id',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='sname',
            new_name='Student_Name',
        ),
    ]
